name: test project
on: [push, workflow_dispatch]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2
      - name: install nodejs
        run: ls 
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies 
        run: npm ci
      - name: listing file
        run: ls -ltrh
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            dist
  deployment:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
          - name: get code
            uses: actions/checkout@v2
          - name: install nodejs
            run: ls 
          - uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: install dependencies 
            run: npm ci
          - name: build project 
            run: npm run build
          - name: deployment
            run: echo deployinggggg....
